"""initial schema

Revision ID: 9a4e8d4aa2b2
Revises: 
Create Date: 2026-09-13 07:50:08.580723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models  # custom column types used below


# revision identifiers, used by Alembic.
revision: str = '9a4e8d4aa2b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=80), nullable=False),
    sa.Column('history_window', sa.Integer(), nullable=False),
    sa.Column('smoothing_constant', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='config_is_a_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'SEATED', 'NO_SHOW', 'CANCELLED', name='partystatus', native_enum=False, length=16), nullable=False),
    sa.Column('quoted_wait_minutes', sa.Integer(), nullable=False),
    sa.Column('joined_at', app.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('notified_at', app.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('seated_at', app.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.models.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('size >= 1', name='party_size_at_least_one'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_token'), ['token'], unique=True)

    op.create_table('bucket_settings',
    sa.Column('bucket', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='sizebucket', native_enum=False, length=16), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('default_turn_minutes', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('bucket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket_settings')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_token'))
        batch_op.drop_index(batch_op.f('ix_parties_status'))
        batch_op.drop_index(batch_op.f('ix_parties_joined_at'))

    op.drop_table('parties')
    op.drop_table('config')
    # ### end Alembic commands ###
